apiVersion: v1
kind: PersistentVolume
metadata:
    name: twistlock-console
    namespace: twistlock
    labels:
        app-volume: twistlock-console
spec:
    accessModes:
        - ReadWriteOnce
        - ReadWriteMany
        - ReadOnlyMany
    capacity:
        storage: 10Gi
    hostPath:
        path: /data/volume1
    persistentVolumeReclaimPolicy: Recycle